baseURL = 'https://howlings.wolftallemo.com/'
languageCode = 'en-us'
theme = 'm10c'
title = "Wolftallemo's Howlings"

[params]
  author = 'Wolftallemo'
  avatar = 'avatar.png'
  description = 'I make (and break) stuff'

[[params.social]]
  icon = 'github'
  name = 'GitHub'
  url = 'https://github.com/Wolftallemo'

[[params.social]]
  icon = 'twitter'
  name = 'Twitter'
  url = 'https://twitter.com/wolftallemo'
